[package]
name = "ilang"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler = { path = "../compiler" }
libffi = "4.0.0"
libloading = "0.8.6"

[dependencies.pyo3]
version = "0.23.4"
features = ["extension-module"]
